// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roberto.DAL;

namespace Roberto.Migrations
{
    [DbContext(typeof(RobertoContext))]
    [Migration("20200728121847_DefaultServiceTable")]
    partial class DefaultServiceTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Roberto.Models.AbImageHome", b =>
                {
                    b.Property<int>("IdAbHome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameImgAbHome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAbHome");

                    b.ToTable("AbImageHomes");
                });

            modelBuilder.Entity("Roberto.Models.AboutUs", b =>
                {
                    b.Property<int>("AbputUs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutHome")
                        .HasColumnType("nvarchar(1300)")
                        .HasMaxLength(1300);

                    b.Property<string>("AboutManagerName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AbputUs");

                    b.ToTable("AboutUs");
                });

            modelBuilder.Entity("Roberto.Models.BedRoom", b =>
                {
                    b.Property<int>("BedRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int?>("ImgId")
                        .HasColumnType("int");

                    b.Property<string>("NameBedRoom")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("NumberAdult")
                        .HasColumnType("int")
                        .HasMaxLength(6);

                    b.Property<int>("NumberChild")
                        .HasColumnType("int")
                        .HasMaxLength(6);

                    b.Property<int>("PiceBedRoom")
                        .HasColumnType("int");

                    b.Property<int>("SizeBedRoom")
                        .HasColumnType("int")
                        .HasMaxLength(500);

                    b.HasKey("BedRoomId");

                    b.HasIndex("ImgId");

                    b.ToTable("BedRooms");
                });

            modelBuilder.Entity("Roberto.Models.DefautService", b =>
                {
                    b.Property<int>("DefaultServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DafaulServiceName")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.HasKey("DefaultServiceId");

                    b.ToTable("DefautServices");
                });

            modelBuilder.Entity("Roberto.Models.Image", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameImg")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ImgId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Roberto.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServiceICon")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Roberto.Models.ServicesRoom", b =>
                {
                    b.Property<int>("ServiceRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BedRoomId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceListName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceRoomId");

                    b.HasIndex("BedRoomId");

                    b.ToTable("ServicesRooms");
                });

            modelBuilder.Entity("Roberto.Models.BedRoom", b =>
                {
                    b.HasOne("Roberto.Models.Image", "Ïmage")
                        .WithMany()
                        .HasForeignKey("ImgId");
                });

            modelBuilder.Entity("Roberto.Models.ServicesRoom", b =>
                {
                    b.HasOne("Roberto.Models.BedRoom", null)
                        .WithMany("servicesRooms")
                        .HasForeignKey("BedRoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
